name: Integreation Tests

on:
  push:
  pull_request:

jobs:
  build:
    name: Compile Firmware
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: make build folder
        run: mkdir build
      - name: create cmake
        run: cd build && cmake ..
      - name: compile
        run: cd build && make

  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: 'cores/portduino'
            exclude: 'FS'
          - 'example'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run clang-format style check for C/C++ programs.
        uses: jidicula/clang-format-action@v4.6.2
        with:
          clang-format-version: '11'
          check-path: ${{ matrix.path }}
